### ISSUE TITLE
Script Editor not opening

### ISSUE THREAD

**Issue by BenjaminEscribano** [kushalkolar/MESmerize#101]
Hi, when I try to open the Script Editor, I get the following error message in the Anaconda Powershell Promt:

EXCEPTION ENCOUNTERED
Traceback (most recent call last):
  File "C:\Users\xxxx\Anaconda3\envs\mesmerize\lib\site-packages\mesmerize\viewer\main_window.py", line 141, in <lambda>
    self.ui.actionScript_Editor.triggered.connect(lambda: self.run_module(script_editor.ModuleGUI))
  File "C:\Users\xxxx\Anaconda3\envs\mesmerize\lib\site-packages\mesmerize\viewer\main_window.py", line 299, in run_module
    m = module_class(self, self._viewer)
  File "C:\Users\xxxx\Anaconda3\envs\mesmerize\lib\site-packages\mesmerize\viewer\modules\script_editor.py", line 27, in __init__
    self.open_temp_script()
  File "C:\Users\xxxx\Anaconda3\envs\mesmerize\lib\site-packages\mesmerize\viewer\modules\script_editor.py", line 72, in open_temp_script
    home_dir = os.environ['HOME']
  File "C:\Users\xxxx\Anaconda3\envs\mesmerize\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

How can I fix this?

**Comment by kushalkolar** [comment]
Mesmerize version?

**Comment by BenjaminEscribano** [comment]
I am using version 0.7.1 on Windows Server 2019 Standard.

**Comment by kushalkolar** [comment]
try running this in the welcome window console:

```python
import os
os.environ["HOME"] = C:\path\to\your\user\dir
```

Press shift + enter to execute stuff in mesmerize consoles
