### ISSUE TITLE
[BUG] CNMFe error

### ISSUE THREAD

**Issue by WhereWolf72** [kushalkolar/MESmerize#103]
Describe the bug
I can import a .tif file using the tiff importer and json_minimal metadata importer. Further, I can run motion correction and inspect the correlation and PNR after running that preliminary analysis. However, when I go to run the full CNMFe analysis, I get an error and don't get an output .hdf5 file, but get the other output files that I have gotten previously upon successful CNMFe analysis. I had this problem previously on an older laptop, but it was fixed when I did a fresh install on a new desktop. Now, I'm attempting to get Mesmerize working on a newer laptop in preparation for the CCN Caiman Workshop in a couple days. Thanks in advance for the help!

To Reproduce

1. open viewer
2. modules > load images > tiff file
3. select file and load asarray, select json file and use json_minimal metadata importer
4. modules > CaImAn Toolbox > CNMF-E
5. input gSig size, enter name, and click "add to batch"
6. Go to batch manager, run the task, double click on task to inspect correlation and PNR values
7. return to CNMF-E window, adjust min_corr and min_pnr values accordingly, enter name for analysis, and click "add to batch"
8. go to batch manager, run the task
9. Upon notification that task has been run, task will be highlighted in red and no .hdf5 file will be output, disallowing visualization of ROIs. Seemingly all other file outputs are present in working directory.

Expected behavior
Upon running full CNMF-E, I expected to get an .hdf5 file along with other file outputs so that I could visualize the ROIs as I have before.

Copy paste message from the error window (if any)
status: 0
output_info: Traceback (most recent call last):
  File "/home/trevor/Desktop/Calcium_Imaging/mez/lib/python3.6/site-packages/mesmerize/viewer/modules/batch_run_modules/CNMFE.py", line 173, in run
    cnm.fit(Y)
  File "/home/trevor/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 606, in fit
    indices=indices)
  File "/home/trevor/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 249, in run_CNMF_patches
    file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f989d7a6240>'. Reason: 'PicklingError("Can't pickle <class '_flapack.error'>: import of module '_flapack' failed",)'

Y.shape: [535, 512, 512]
processing_time: 0.6470573385556538

**Copy-paste or take a screenshot of the terminal that Mesmerize is running in**
```
home/user/Desktop/Calcium_Imaging/mez/lib/python3.6/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
Loading, please wait... 
%(asctime)s %(levelname)s %(pathname)s %(lineno)s 
 %(message)s 
Moving old logfiles...
Moving old logfiles...
%(asctime)s %(levelname)s %(pathname)s %(lineno)s 
 %(message)s 
starting batch mananger
starting batch mananger
showing corr pnr


```
_Make sure the entire stack trace is visible, and all messages relevant to the issue are visible._

**If relevant, messages from the batch manager terminal**
![image](https://user-images.githubusercontent.com/92590376/171317532-dd4ceac1-8b52-4365-80fd-94710a109e0b.png)

**Screenshots**

**Operating System & specs (CPU, RAM etc.). Please complete the following information:**
 - OS: Ubuntu 20.04 LTS
 - CPU: Intel i7-9750H
 - RAM: 32 GiB
 - GPU: GeForce GTX 1650 Mobile Max Q

**Details about your Mesmerize install**
  - Are you using anaconda or venv (the python built-in virtual environment management) Venv
  - Are you using the pip install, If so which version?** pip = 22.1.2
  - Are you using a clone of the master branch from the GitHub repo installed in development mode? I installed per the Mesmerize instructions for linux. The only thing I believe was cloned was the CaImAn install.

**Environment**
 - Please provide a list of installed packages and their versions, run `pip list` in your environment
 ```
Package                       Version     Editable project location
----------------------------- ----------- -------------------------
absl-py                       1.0.0
alabaster                     0.7.12
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
astor                         0.8.1
astroid                       2.11.5
astunparse                    1.6.3
async-generator               1.10
attrs                         21.4.0
Babel                         2.10.1
backcall                      0.2.0
bleach                        4.1.0
bokeh                         2.3.3
Bottleneck                    1.2.1
cachetools                    4.2.4
caiman                        1.8.8       /home/user/CaImAn
certifi                       2022.5.18.1
cffi                          1.15.0
chardet                       4.0.0
charset-normalizer            2.0.12
click                         8.0.4
cloudpickle                   2.1.0
colorcet                      3.0.0
cryptography                  37.0.2
cycler                        0.10.0
Cython                        0.29.30
dask                          2021.3.0
dataclasses                   0.8
decorator                     4.4.2
defusedxml                    0.7.1
dill                          0.3.4
docutils                      0.18.1
entrypoints                   0.4
future                        0.18.2
gast                          0.3.3
google-auth                   1.35.0
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
graphviz                      0.19.1
grpcio                        1.46.3
h5py                          2.10.0
hdmf                          2.5.8
holoviews                     1.14.9
idna                          3.3
imageio                       2.15.0
imagesize                     1.3.0
importlib-metadata            4.8.3
importlib-resources           5.4.0
ipykernel                     5.5.6
ipyparallel                   8.2.1
ipython                       7.16.3
ipython-genutils              0.2.0
ipywidgets                    7.7.0
isort                         5.10.1
jedi                          0.17.2
jeepney                       0.7.1
Jinja2                        3.0.3
joblib                        1.1.0
jsonschema                    3.2.0
jupyter                       1.0.0
jupyter-client                7.1.2
jupyter-console               6.4.3
jupyter-core                  4.9.2
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.1.0
Keras-Applications            1.0.8
Keras-Preprocessing           1.1.2
keyring                       23.4.1
kiwisolver                    1.3.1
lazy-object-proxy             1.7.1
llvmlite                      0.36.0
Markdown                      3.3.7
MarkupSafe                    2.0.1
matplotlib                    3.2.1
mccabe                        0.7.0
mesmerize                     0.7.1
mistune                       0.8.4
nbclient                      0.5.9
nbconvert                     6.0.7
nbformat                      5.1.3
nest-asyncio                  1.5.5
networkx                      2.5.1
notebook                      6.4.10
numba                         0.53.1
numexpr                       2.8.1
numpy                         1.19.5
numpydoc                      1.1.0
nuset-lib                     0.2.0
oauthlib                      3.2.0
opencv-contrib-python         4.5.5.64
opencv-python                 4.5.5.64
opt-einsum                    3.3.0
packaging                     21.3
pandas                        1.1.5
pandocfilters                 1.5.0
panel                         0.12.1
param                         1.12.1
parso                         0.7.1
PeakUtils                     1.3.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.4.0
pip                           21.3.1
platformdirs                  2.4.0
prometheus-client             0.14.1
prompt-toolkit                3.0.29
protobuf                      3.19.4
psutil                        5.9.1
ptyprocess                    0.7.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.8.0
pycparser                     2.21
pyct                          0.4.8
pyflakes                      2.4.0
Pygments                      2.12.0
pylint                        2.13.9
pynwb                         1.5.1
pyparsing                     3.0.9
PyQt5                         5.12
PyQt5_sip                     4.19.19
pyqtgraph                     0.11.1
pyrsistent                    0.18.0
python-dateutil               2.8.2
pytz                          2022.1
pyviz-comms                   2.2.0
PyWavelets                    1.1.1
PyYAML                        6.0
pyzmq                         23.0.0
qtap                          0.1.2
QtAwesome                     1.1.1
qtconsole                     5.2.2
QtPy                          2.0.1
requests                      2.27.1
requests-oauthlib             1.3.1
rope                          1.1.1
rsa                           4.8
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
scikit-image                  0.15.0
scikit-learn                  0.23.2
scipy                         1.4.1
seaborn                       0.9.0
SecretStorage                 3.3.2
Send2Trash                    1.8.0
setuptools                    59.6.0
six                           1.16.0
sk-video                      1.1.10
snowballstemmer               2.2.0
Sphinx                        5.0.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        3.3.3
spyder-kernels                0.5.2
tables                        3.7.0
Tcl                           0.2
tensorboard                   2.2.2
tensorboard-plugin-wit        1.8.1
tensorflow                    2.2.0
tensorflow-estimator          2.2.0
tensorflow-gpu                1.15.5
termcolor                     1.1.0
terminado                     0.12.1
testpath                      0.6.0
threadpoolctl                 3.1.0
tifffile                      2020.9.3
tk                            0.1.0
tomli                         1.2.3
tornado                       6.1
tqdm                          4.64.0
traitlets                     4.3.3
tslearn                       0.4.1
typed-ast                     1.5.4
typing_extensions             4.1.1
urllib3                       1.26.9
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      2.0.3
wheel                         0.37.1
widgetsnbextension            3.6.0
wrapt                         1.14.1
wurlitzer                     3.0.2
zipp                          3.6.0

 ```

 
**Additional context**
Just in case it was a similar problem to my previous bug report (#82), I followed the suggested steps around liblapack and libopenblas, but it didn't fix the issue. I did get an error surrounding tensorflow-gpu's dependencies (see below), but I don't believe that I'm even utilizing that package for this step.

Tensorflow dependency error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-gpu 1.15.5 requires gast==0.2.2, but you have gast 0.3.3 which is incompatible.
tensorflow-gpu 1.15.5 requires numpy<1.19.0,>=1.16.0, but you have numpy 1.19.5 which is incompatible.
tensorflow-gpu 1.15.5 requires tensorboard<1.16.0,>=1.15.0, but you have tensorboard 2.2.2 which is incompatible.
tensorflow-gpu 1.15.5 requires tensorflow-estimator==1.15.1, but you have tensorflow-estimator 2.2.0 which is incompatible.

```

**Comment by kushalkolar** [comment]
Mesmerize and caiman version?

I you can't get it working by late this afternoon just use the VM for the
workshop.
