### ISSUE TITLE
Probable multiprocessing issue on Windows 10

### ISSUE THREAD

**Issue by kushalkolar** [kushalkolar/MESmerize#40]
Need to confirm on another machine. Can probably be fixed with `if __name___ == "__main__" `

```
The term 'export' is not recognized as the name of a cmdlet, function, script f

ile, or operable program. Check the spelling of the name, or if a path was incl
uded, verify that the path is correct and try again.
At D:\NewFolder\PVC-7\fc94d298-5fc4-42ce-a399-3f7db8ac4e45.ps1:8 char:7
+ export <<<< OPENBLAS_NUM_THREADS=3
 + CategoryInfo : ObjectNotFound: (export:String) [], CommandNotFo
 undException
 + FullyQualifiedErrorId : CommandNotFoundException


C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
 _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
 _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
 _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
 _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
 _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
 np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
 _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
 _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
 _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
 _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
 _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
 np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.cluster.k_means_ module is deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
 warnings.warn(message, FutureWarning)
Traceback (most recent call last):
 File "<string>", line 1, in <module>
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\multiprocessing\spawn.py", line 105, in spawn_main
 exitcode = _main(fd)
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\multiprocessing\spawn.py", line 114, in _main
 prepare(preparation_data)
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\multiprocessing\spawn.py", line 225, in prepare
 _fixup_main_from_path(data['init_main_from_path'])
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
 run_name="__mp_main__")
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\runpy.py", line 263, in run_path
 pkg_name=pkg_name, script_name=fname)
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\runpy.py", line 96, in _run_module_code
 mod_name, mod_spec, pkg_name, script_name)
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\runpy.py", line 85, in _run_code
 exec(code, run_globals)
 File "c:\users\maria2\anaconda3\envs\mesmerize\lib\site-packages\mesmerize\viewer\modules\batch_run_modules\CNMF.py", line 34, in <module>
 from mesmerize.common.utils import HdfTools
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\mesmerize\__init__.py", line 1, in <module>
 from .analysis import *
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\mesmerize\analysis\__init__.py", line 3, in <module>
 from .math import cross_correlation, drfft_dtw, tvregdiff
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\site-packages\mesmerize\analysis\math\drfft_dtw.py", line 17, in <module>
 raw_curve: np.ndarray = None, rf_curve: np.ndarray = None) -> list:
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\multiprocessing\context.py", line 56, in Manager
 m.start()
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\multiprocessing\managers.py", line 513, in start
 self._process.start()
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\multiprocessing\process.py", line 105, in start
 self._popen = self._Popen(self)
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\multiprocessing\context.py", line 322, in _Popen
 return Popen(process_obj)
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
 prep_data = spawn.get_preparation_data(process_obj._name)
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
 _check_not_importing_main()
 File "C:\Users\Maria2\Anaconda3\envs\mesmerize\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
 is not going to be frozen to produce an executable.''')
RuntimeError:
 An attempt has been made to start a new process before the
 current process has finished its bootstrapping phase.

 This probably means that you are not using fork to start your
 child processes and you have forgotten to use the proper idiom
 in the main module:

 if __name__ == '__main__':
 freeze_support()
 ...

 The "freeze_support()" line can be omitted if the program
 is not going to be frozen to produce an executable.

===== 2020.12.02 14:12:46 =====
```

**Comment by kushalkolar** [comment]
Fixed, see #48
