### ISSUE TITLE
[BUG] mesmerize sometimes hangs on logfile removal and will not open

### ISSUE THREAD

**Issue by EricThomson** [kushalkolar/MESmerize#55]
**Describe the bug**
After using mesmerize successfully, when I try to start it again, I get the message that it cannot because some old logfiles are being used by another process.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Run mesmerize (sometimes a few times)
2. Start another instances of powershell, and the mesmerize environment, and try to start mesmerize. 

**Expected behavior**
Mesmerize should start.

**Copy paste message from the error window (if any)**

> EXCEPTION ENCOUNTERED
> Traceback (most recent call last):
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\lab_user\miniconda3\envs\mesmerize\Scripts\mesmerize.exe\__main__.py", line 7, in <module>
>     sys.exit(main())
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\site-packages\click\core.py", line 1134, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\site-packages\click\core.py", line 1059, in main
>     rv = self.invoke(ctx)
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\site-packages\click\core.py", line 1401, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\site-packages\click\core.py", line 767, in invoke
>     return __callback(*args, **kwargs)
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\site-packages\mesmerize\__main__.py", line 132, in main
>     move_old_logfiles(root_logger, log_file_dir)
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\site-packages\mesmerize\__main__.py", line 75, in move_old_logfiles
>     os.remove(old_logfile)
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\lab_user\\.mesmerize\\2021-05-25_13.29.41-279226.log'
> EXCEPTION ENCOUNTERED
> Traceback (most recent call last):
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\lab_user\miniconda3\envs\mesmerize\Scripts\mesmerize.exe\__main__.py", line 7, in <module>
>     sys.exit(main())
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\site-packages\click\core.py", line 1134, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\site-packages\click\core.py", line 1059, in main
>     rv = self.invoke(ctx)
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\site-packages\click\core.py", line 1401, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\site-packages\click\core.py", line 767, in invoke
>     return __callback(*args, **kwargs)
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\site-packages\mesmerize\__main__.py", line 132, in main
>     move_old_logfiles(root_logger, log_file_dir)
>   File "c:\users\lab_user\miniconda3\envs\mesmerize\lib\site-packages\mesmerize\__main__.py", line 75, in move_old_logfiles
>     os.remove(old_logfile)
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\lab_user\\.mesmerize\\2021-05-25_13.29.41-279226.log'

**Copy-paste or take a screenshot of the terminal that Mesmerize is running in**
![image](https://user-images.githubusercontent.com/6643322/119543381-99369a00-bd5e-11eb-8b8f-97f2484e0b89.png)

**Operating System & specs (CPU, RAM etc.). Please complete the following information:**
Windows 10, 128GB Ram

**Details about your Mesmerize install**
mamba for caiman, pip for mesmerize

**Additional context**
This has happened a few times. When I manually delete the log files things work fine.

**Comment by kushalkolar** [comment]
Thanks, looks like I need to figure out how process file permissions really work in Windows, bypassed moving old logfiles in windows for now.

**Comment by EricThomson** [comment]
Sorry I'm not more help -- at some point I plan to actually start to read the code I'm currently just working through the pipeline.

**Comment by kushalkolar** [comment]
No worries, we haven't tested it extensively on Windows, I'm happy to see that you're trying things out.
