### ISSUE TITLE
CaImAn Install Issue - Windows/Linux Dual Boot[INSTALLATION HELP]

### ISSUE THREAD

**Issue by WhereWolf72** [kushalkolar/MESmerize#71]
**System information**
1. OS (Windows 10/Ubuntu 20.04 LTS Dual Boot [run on Ubuntu partition])
2. CPU (Intel(R) Core(TM) i7-9750H)
3. RAM (32Gb)
4. Do you have an SSD or magnetic HDD (SSD)

**Copy & paste the entire output of the terminal while you were trying to install when the issue came up:**

```
/home/user/.local/lib/python3.8/site-packages/mesmerize/common/configuration.py:37: UserWarning: Caiman package not found. Caiman features will be disabled.
  warn(
2021-10-21 11:14:33.297075: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-21 11:14:33.297096: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/user/.local/lib/python3.8/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)
Loading, please wait... 
%(asctime)s %(levelname)s %(pathname)s %(lineno)s 
 %(message)s 
Moving old logfiles...
Moving old logfiles...
QApplication::exec: Please instantiate the QApplication object first
Segmentation fault (core dumped)

```

**Installation method**
1. Are you using anaconda, python virtual environments, or something else?
 conda 4.10.3, but installed with mamba

2. If you're installing mesmerize through pip, what version of pip is installed in the environment?
pip 21.3
3. Are you trying to install in developer mode from the repo?
No
4. What is the python version in the environment you're trying to install `mesmerize` in?
python=3.8
5. Information if you're using some other installation method.
Installed caiman using mamba in a conda environment. I can see caiman in the environment, but there seems to be issues, even after using caimanmanager.py. I believe it may stem from dependency issues from tensorflow.

**Comment by kushalkolar** [comment]
This looks like a Qt mismatch, possibly due to opencv. Can you try:

```
pip uninstall opencv-python
pip install opencv-python-headless
```

**Comment by WhereWolf72** [comment]
After running your suggestions and then attempting to open mesmerize, I got the following:

_/home/user/.local/lib/python3.8/site-packages/mesmerize/common/configuration.py:37: UserWarning: Caiman package not found. Caiman features will be disabled.
  warn(
2021-10-21 23:33:10.970995: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-10-21 23:33:10.971069: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
===== 2021.10.21 23:10:13 =====
Traceback (most recent call last):
  File "/home/user/.local/bin/mesmerize", line 5, in <module>
    from mesmerize.__main__ import main
  File "/home/user/.local/lib/python3.8/site-packages/mesmerize/__init__.py", line 1, in <module>
    from .analysis import *
  File "/home/user/.local/lib/python3.8/site-packages/mesmerize/analysis/__init__.py", line 3, in <module>
    from .math import cross_correlation, drfft_dtw, tvregdiff
  File "/home/user/.local/lib/python3.8/site-packages/mesmerize/analysis/math/drfft_dtw.py", line 7, in <module>
    from ...plotting.variants.timeseries import TimeseriesPlot
  File "/home/user/.local/lib/python3.8/site-packages/mesmerize/plotting/__init__.py", line 1, in <module>
    from .variants import *
  File "/home/user/.local/lib/python3.8/site-packages/mesmerize/plotting/variants/__init__.py", line 1, in <module>
    from .heatmap import Heatmap
  File "/home/user/.local/lib/python3.8/site-packages/mesmerize/plotting/variants/heatmap.py", line 13, in <module>
    from ...pyqtgraphCore.widgets.MatplotlibWidget import MatplotlibWidget
  File "/home/user/.local/lib/python3.8/site-packages/mesmerize/pyqtgraphCore/__init__.py", line 266, in <module>
    from .imageview import *
  File "/home/user/.local/lib/python3.8/site-packages/mesmerize/pyqtgraphCore/imageview/__init__.py", line 6, in <module>
    from .ImageView import ImageView
  File "/home/user/.local/lib/python3.8/site-packages/mesmerize/pyqtgraphCore/imageview/ImageView.py", line 40, in <module>
    from ...viewer.core.viewer_work_environment import ViewerWorkEnv
  File "/home/user/.local/lib/python3.8/site-packages/mesmerize/viewer/__init__.py", line 1, in <module>
    from .main_window import MainWindow as ViewerWindow
  File "/home/user/.local/lib/python3.8/site-packages/mesmerize/viewer/main_window.py", line 19, in <module>
    from .modules import *
  File "/home/user/.local/lib/python3.8/site-packages/mesmerize/viewer/modules/femtonics_mesc.py", line 16, in <module>
    from cv2 import bitwise_not
ModuleNotFoundError: No module named 'cv2'_


I then tried to install cv2, but got the following error:

_ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2_

**Comment by kushalkolar** [comment]
did you `pip install opencv-python-headless`
