### ISSUE TITLE
[INSTALLATION HELP]

### ISSUE THREAD

**Issue by kevinpan0127** [kushalkolar/MESmerize#80]
Operating System & specs (CPU, RAM etc.)
MacOS Monterey, Apple M1 pro, 32GB RAM

Details about your Mesmerize install
Followed installation on the mesmerize document page for MacOS except for caiman installation. 
Used "mamba create -n caiman -c conda-forge caiman" after "source activate mesmerize" as the original code gets stuck at solving environment 

Describe the issue, please be as explicit and detailed as possible.
I have finished all installation steps, however when opening mesmerize, this is the error i am getting:

(mesmerize) kevin@Kevins-MacBook-Pro ~ % mesmerize
Traceback (most recent call last):
  File "/opt/anaconda3/envs/mesmerize/bin/mesmerize", line 5, in <module>
    from mesmerize.__main__ import main
  File "/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/mesmerize/__init__.py", line 1, in <module>
    from .analysis import *
  File "/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/mesmerize/analysis/__init__.py", line 1, in <module>
    from .data_types import Transmission
  File "/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/mesmerize/analysis/data_types.py", line 14, in <module>
    import pandas as pd
  File "/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/pandas/core/api.py", line 5, in <module>
    from pandas.core.arrays.integer import (
  File "/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/pandas/core/arrays/__init__.py", line 13, in <module>
    from .sparse import SparseArray  # noqa: F401
  File "/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/pandas/core/arrays/sparse/__init__.py", line 3, in <module>
    from pandas.core.arrays.sparse.accessor import SparseAccessor, SparseFrameAccessor
  File "/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/pandas/core/arrays/sparse/accessor.py", line 10, in <module>
    from pandas.core.arrays.sparse.array import SparseArray
  File "/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/pandas/core/arrays/sparse/array.py", line 44, in <module>
    from pandas.core.arrays.sparse.dtype import SparseDtype
  File "/opt/anaconda3/envs/mesmerize/lib/python3.6/site-packages/pandas/core/arrays/sparse/dtype.py", line 9, in <module>
    from pandas._typing import Dtype, DtypeObj
ImportError: cannot import name 'DtypeObj'

How should I be able to solve this? Thank you!

**Comment by kushalkolar** [comment]
Can you please try this
https://stackoverflow.com/questions/68926935/importerror-cannot-import-name-dtypearg-from-pandas

**Comment by kushalkolar** [comment]
@kevinpan0127

There are some weird issues with python3.6 and newer packages right now. We're working on updating the installation, these instructions are not finalized yet but it's worth giving it a shot:

1. Create an `environment.yml` file with the following contents

```yaml
name: mesmerize

channels:
  - conda-forge

# From the conda ecosystem.
dependencies:
  - python=3.8
  - pip
  - tensorflow==2.4
  - caiman==1.9.4
  # From the PyPI ecosystem.
  - pip:
    - tslearn==0.4.1
    - mesmerize
```

2. Run:

```
mamba create -n mesmerize && mamba env update -n mesmerize --f environment.yml
```

**Comment by kevinpan0127** [comment]
I was able to get it installed using "mamba install -c conda-forge caiman" and reinstalling mesmerize...

**Comment by kushalkolar** [comment]
Thanks for sharing how you fixed it!
