### ISSUE TITLE
[BUG] <CNMF>

### ISSUE THREAD

**Issue by daiyh98** [kushalkolar/MESmerize#94]
status: 0
output_info: Traceback (most recent call last):
  File "/home/donglab/mesmerize/lib/python3.6/site-packages/mesmerize/viewer/modules/batch_run_modules/CNMF.py", line 60, in run
    run_single(batch_dir, UUID, output)
  File "/home/donglab/mesmerize/lib/python3.6/site-packages/mesmerize/viewer/modules/batch_run_modules/CNMF.py", line 158, in run_single
    cnm.save(out_filename)
  File "/home/donglab/mesmerize/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 667, in save
    save_dict_to_hdf5(self.__dict__, filename)
  File "/home/donglab/mesmerize/CaImAn/caiman/utils/utils.py", line 429, in save_dict_to_hdf5
    recursively_save_dict_contents_to_group(h5file, subdir, dic)
  File "/home/donglab/mesmerize/CaImAn/caiman/utils/utils.py", line 524, in recursively_save_dict_contents_to_group
    recursively_save_dict_contents_to_group(h5file, path + key + '/', item.__dict__)
  File "/home/donglab/mesmerize/CaImAn/caiman/utils/utils.py", line 509, in recursively_save_dict_contents_to_group
    recursively_save_dict_contents_to_group(h5file, path + key + '/', item)
  File "/home/donglab/mesmerize/CaImAn/caiman/utils/utils.py", line 496, in recursively_save_dict_contents_to_group
    raise ValueError('Error while saving {}.'.format(key))
ValueError: Error while saving var_name_hdf5.

**Comment by daiyh98** [comment]
this error happens when everything seems to be done in a CNMF processing,

**Comment by kushalkolar** [comment]
Please follow the issue template and provide all details.
