### ISSUE TITLE
[BUG] <CNMF saving bug>

### ISSUE THREAD

**Issue by daiyh98** [kushalkolar/MESmerize#95]
**Describe the bug**
hello, I performed the CNMF plugin on a tiff image. Everything went well until it raised an error on saving files in the end 

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to 'batch manager'
2. Click on 'start'
3. Scroll down to 'output'

**Expected behavior**
I wished it could successfully finish CNMF algorithm and when I double click the batch name, I could see the final segmentation result

**Copy paste message from the error window (if any)**
status: 0
output_info: Traceback (most recent call last):
File "/home/donglab/mesmerize/lib/python3.6/site-packages/mesmerize/viewer/modules/batch_run_modules/CNMF.py", line 60, in run
run_single(batch_dir, UUID, output)
File "/home/donglab/mesmerize/lib/python3.6/site-packages/mesmerize/viewer/modules/batch_run_modules/CNMF.py", line 158, in run_single
cnm.save(out_filename)
File "/home/donglab/mesmerize/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 667, in save
save_dict_to_hdf5(self.dict, filename)
File "/home/donglab/mesmerize/CaImAn/caiman/utils/utils.py", line 429, in save_dict_to_hdf5
recursively_save_dict_contents_to_group(h5file, subdir, dic)
File "/home/donglab/mesmerize/CaImAn/caiman/utils/utils.py", line 524, in recursively_save_dict_contents_to_group
recursively_save_dict_contents_to_group(h5file, path + key + '/', item.dict)
File "/home/donglab/mesmerize/CaImAn/caiman/utils/utils.py", line 509, in recursively_save_dict_contents_to_group
recursively_save_dict_contents_to_group(h5file, path + key + '/', item)
File "/home/donglab/mesmerize/CaImAn/caiman/utils/utils.py", line 496, in recursively_save_dict_contents_to_group
raise ValueError('Error while saving {}.'.format(key))
ValueError: Error while saving var_name_hdf5.
**Copy-paste or take a screenshot of the terminal that Mesmerize is running in**
```
![9de439490c4202be13972999e0fdb0b](https://user-images.githubusercontent.com/43029102/159273828-7d6250bc-0bee-4329-b98d-a218cb5b3643.png)
```
_Make sure the entire stack trace is visible, and all messages relevant to the issue are visible._

**If relevant, messages from the batch manager terminal**

**Operating System & specs (CPU, RAM etc.). Please complete the following information:**
 - OS:  Ubuntu 18.04.6 LTS

**Details about your Mesmerize install**
  - using python3.6 venv (not anaconda)
  - forgot wether I used pip, just followed the instruction
  - no clone

**Environment**
 - Please provide a list of installed packages and their versions, run `pip list` in your environment
 ```
 absl-py                       0.15.0
alabaster                     0.7.12
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
astor                         0.8.1
astroid                       2.9.3
astunparse                    1.6.3
async-generator               1.10
attrs                         21.4.0
Babel                         2.9.1
backcall                      0.2.0
bleach                        4.1.0
bokeh                         2.3.3
Bottleneck                    1.2.1
cached-property               1.5.2
cachetools                    4.2.4
caiman                        1.8.8     /home/donglab/mesmerize/CaImAn
certifi                       2021.10.8
cffi                          1.15.0
chardet                       4.0.0
charset-normalizer            2.0.12
clang                         5.0
click                         8.0.4
cloudpickle                   2.0.0
colorcet                      3.0.0
cryptography                  36.0.1
cycler                        0.10.0
Cython                        0.29.28
dask                          2021.3.0
dataclasses                   0.8
decorator                     4.4.2
defusedxml                    0.7.1
docutils                      0.17.1
entrypoints                   0.4
flatbuffers                   1.12
future                        0.18.2
gast                          0.4.0
google-auth                   1.35.0
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
graphviz                      0.19.1
grpcio                        1.44.0
h5py                          3.1.0
hdmf                          2.5.8
holoviews                     1.14.8
idna                          3.3
imageio                       2.15.0
imagesize                     1.3.0
importlib-metadata            4.8.3
importlib-resources           5.4.0
ipykernel                     5.5.6
ipyparallel                   8.2.0
ipython                       7.16.3
ipython-genutils              0.2.0
ipywidgets                    7.6.5
isort                         5.10.1
jedi                          0.17.2
jeepney                       0.7.1
Jinja2                        3.0.3
joblib                        1.1.0
jsonschema                    3.2.0
jupyter                       1.0.0
jupyter-client                7.1.2
jupyter-console               6.4.0
jupyter-core                  4.9.2
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.0.2
keras                         2.6.0
Keras-Applications            1.0.8
Keras-Preprocessing           1.1.2
keyring                       23.4.1
kiwisolver                    1.3.1
lazy-object-proxy             1.7.1
llvmlite                      0.36.0
Markdown                      3.3.6
MarkupSafe                    2.0.1
matplotlib                    3.2.1
mccabe                        0.6.1
mesmerize                     0.7.1
mistune                       0.8.4
nbclient                      0.5.9
nbconvert                     6.0.7
nbformat                      5.1.3
nest-asyncio                  1.5.4
networkx                      2.5.1
notebook                      6.4.8
numba                         0.53.1
numexpr                       2.8.1
numpy                         1.19.5
numpydoc                      1.1.0
nuset-lib                     0.2.0
oauthlib                      3.2.0
opencv-contrib-python         4.5.5.62
opencv-python-headless        4.5.5.64
opt-einsum                    3.3.0
packaging                     21.3
pandas                        1.1.5
pandocfilters                 1.5.0
panel                         0.12.1
param                         1.12.0
parso                         0.7.1
PeakUtils                     1.3.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.4.0
pip                           21.3.1
pkg_resources                 0.0.0
platformdirs                  2.4.0
prometheus-client             0.13.1
prompt-toolkit                3.0.28
protobuf                      3.19.4
psutil                        5.9.0
ptyprocess                    0.7.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.8.0
pycparser                     2.21
pyct                          0.4.8
pyflakes                      2.4.0
Pygments                      2.11.2
pylint                        2.12.2
pynwb                         1.5.1
pyparsing                     3.0.7
PyQt5                         5.12
PyQt5_sip                     4.19.19
pyqtgraph                     0.11.1
pyrsistent                    0.18.0
python-dateutil               2.8.2
pytz                          2021.3
pyviz-comms                   2.1.0
PyWavelets                    1.1.1
PyYAML                        6.0
pyzmq                         22.3.0
qtap                          0.1.2
QtAwesome                     1.1.1
qtconsole                     5.2.2
QtPy                          2.0.1
requests                      2.27.1
requests-oauthlib             1.3.1
rope                          0.23.0
rsa                           4.8
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
scikit-image                  0.15.0
scikit-learn                  0.23.2
scipy                         1.4.1
seaborn                       0.9.0
SecretStorage                 3.3.1
Send2Trash                    1.8.0
setuptools                    59.6.0
six                           1.15.0
sk-video                      1.1.10
snowballstemmer               2.2.0
Sphinx                        4.4.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        3.3.3
spyder-kernels                0.5.2
tables                        3.7.0
Tcl                           0.2
tensorboard                   2.6.0
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.6.2
tensorflow-estimator          2.6.0
tensorflow-gpu                1.15.5
termcolor                     1.1.0
terminado                     0.12.1
testpath                      0.6.0
threadpoolctl                 3.1.0
tifffile                      2020.9.3
tk                            0.1.0
toml                          0.10.2
tornado                       6.1
tqdm                          4.63.0
traitlets                     4.3.3
tslearn                       0.4.1
typed-ast                     1.5.2
typing-extensions             3.7.4.3
urllib3                       1.26.8
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      2.0.3
wheel                         0.37.1
widgetsnbextension            3.5.2
wrapt                         1.12.1
wurlitzer                     3.0.2
zipp                          3.6.0
 ```
**Additional context**

**Comment by kushalkolar** [comment]
Caiman requires `h5py` v2.10.0:

```
pip uninstall h5py && pip install h5py~=2.10.0
```

**Comment by kushalkolar** [comment]
@daiyh98 did this fix the issue?

**Comment by kushalkolar** [comment]
closing due to inactivity
